services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SMARTY_API_TOKEN=${SMARTY_API_TOKEN}
      - WORK_API_TOKEN=${WORK_API_TOKEN}
    volumes:
      - ./app:/app