version: "3.8"

services:
  python-app:
    build: ./python-app
    ports:
      - "5000:5000"

  php-app:
    build: ./php-app
    ports:
      - "8080:8080"
    volumes:
      - ./php-app:/var/www/html
